# Generated by Django 5.0 on 2024-01-04 21:56

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created_at"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="modified_at"),
                ),
                (
                    "is_safe_deleted",
                    models.BooleanField(default=False, verbose_name="is_safe_delete"),
                ),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                (
                    "mobile",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        max_length=128,
                        null=True,
                        region=None,
                        unique=True,
                        verbose_name="mobile",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=150, null=True, verbose_name="email"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        default=[("Male", "Male"), ("Female", "Female")],
                        max_length=50,
                        verbose_name="gender",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("New", "New"),
                            ("Contacted", "Contacted"),
                            ("Disqualified", "Disqualified"),
                        ],
                        default="New",
                        max_length=50,
                        verbose_name="status",
                    ),
                ),
                ("notes", models.TextField(null=True, verbose_name="notes")),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="address"
                    ),
                ),
                (
                    "occupation",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="occupation"
                    ),
                ),
                (
                    "organization",
                    models.TextField(
                        blank=True, null=True, verbose_name="organization"
                    ),
                ),
                (
                    "website",
                    models.URLField(blank=True, null=True, verbose_name="website"),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Social Media", "Social Media"),
                            ("Walk-In", "Walk-In"),
                            ("Friend Recommendation", "Friend Recommendation"),
                        ],
                        max_length=150,
                        null=True,
                        verbose_name="lead_source",
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assigned_to_leads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Lead",
                "verbose_name_plural": "Leads",
            },
        ),
    ]
