# Generated by Django 5.0 on 2024-01-08 22:16

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0002_lead_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="mobile",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region=None, unique=True, verbose_name="mobile"
            ),
        ),
    ]
