# Generated by Django 5.0 on 2023-12-29 23:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created_at"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="modified_at"),
                ),
                (
                    "is_safe_deleted",
                    models.BooleanField(default=False, verbose_name="is_safe_delete"),
                ),
                ("start_date", models.DateField(auto_now_add=True)),
                ("end_date", models.DateField(null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_class_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Class Subscription",
                "verbose_name_plural": "Class Subscriptions",
            },
        ),
        migrations.CreateModel(
            name="ClassAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created_at"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="modified_at"),
                ),
                (
                    "is_safe_deleted",
                    models.BooleanField(default=False, verbose_name="is_safe_delete"),
                ),
                ("is_attended", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_class_attendances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="class_subscription_attendances",
                        to="sport_classes.classsubscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "Class Attendance",
                "verbose_name_plural": "Class Attendance",
            },
        ),
        migrations.CreateModel(
            name="SportClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created_at"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="modified_at"),
                ),
                (
                    "is_safe_deleted",
                    models.BooleanField(default=False, verbose_name="is_safe_delete"),
                ),
                ("name", models.CharField(max_length=150)),
                ("dates", models.CharField(blank=True, max_length=255, null=True)),
                ("time_from", models.TimeField(blank=True, null=True)),
                ("time_to", models.TimeField(blank=True, null=True)),
                ("maximum_capacity", models.IntegerField(default=0)),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")],
                        default="Male",
                        max_length=50,
                    ),
                ),
                ("age_group", models.IntegerField(default=0)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="instructor_sport_classes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Sport Class",
                "verbose_name_plural": "Sport Classes",
            },
        ),
        migrations.AddField(
            model_name="classsubscription",
            name="sport_class",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sport_class_subscriptions",
                to="sport_classes.sportclass",
            ),
        ),
    ]
