# Generated by Django 5.0 on 2023-12-25 21:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_system_admin",
            field=models.BooleanField(default=False, verbose_name="is_system_admin"),
        ),
    ]
