# Generated by Django 5.0 on 2023-12-27 17:56

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0003_remove_user_is_system_admin_alter_user_groups"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="is_mobile_verified",
            new_name="is_whatsapp_verified",
        ),
        migrations.AddField(
            model_name="user",
            name="whatsapp_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                max_length=128,
                null=True,
                region=None,
                unique=True,
                verbose_name="whatsapp_number",
            ),
        ),
    ]
