# Generated by Django 5.0 on 2024-01-05 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "clients",
            "0004_rename_is_mobile_verified_user_is_whatsapp_verified_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="referred_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="referred_by_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
