# Generated by Django 5.0 on 2024-01-10 18:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0007_alter_user_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="referred_by",
        ),
    ]
