# Generated by Django 5.0 on 2024-01-03 22:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Academy_class", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SportClass",
            new_name="AcademyClass",
        ),
        migrations.AlterModelOptions(
            name="academyclass",
            options={
                "verbose_name": "Academy Class",
                "verbose_name_plural": "Academy Classes",
            },
        ),
        migrations.RemoveField(
            model_name="classsubscription",
            name="sport_class",
        ),
        migrations.AddField(
            model_name="classsubscription",
            name="academy_class",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="academy_class_subscriptions",
                to="Academy_class.academyclass",
            ),
        ),
    ]
