# Generated by Django 5.0 on 2024-01-04 21:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Academy_class", "0002_rename_sportclass_academyclass_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="academyclass",
            name="age_group",
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
        migrations.AlterField(
            model_name="academyclass",
            name="dates",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
