# Generated by Django 5.0 on 2024-01-30 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Academy_class", "0004_alter_classattendance_subscription_and_more"),
        ("subscriptions", "0016_subscription_refunded_amount_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="classattendance",
            name="walk_in_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="walk_in_user_class_attendance",
                to="subscriptions.walkinuser",
            ),
        ),
        migrations.AlterField(
            model_name="classattendance",
            name="subscription",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="class_subscription_attendances",
                to="subscriptions.subscription",
            ),
        ),
        migrations.AlterField(
            model_name="classattendance",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="user_class_attendances",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
