# Generated by Django 5.0 on 2024-02-04 20:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Academy_class", "0006_remove_academyclass_dates"),
    ]

    operations = [
        migrations.AddField(
            model_name="academyclass",
            name="dates",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.DateField(), blank=True, null=True, size=None
            ),
        ),
    ]
