# Generated by Django 5.0 on 2024-01-05 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created_at"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="modified_at"),
                ),
                (
                    "is_safe_deleted",
                    models.BooleanField(default=False, verbose_name="is_safe_delete"),
                ),
                ("title", models.CharField(max_length=255)),
                ("details", models.TextField(blank=True, null=True)),
                ("deadline", models.DateField()),
                (
                    "reminder_intervals",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("New", "New"),
                            ("Pending", "Pending"),
                            ("In progress", "In progress"),
                            ("Completed", "Completed"),
                        ],
                        default="New",
                        max_length=50,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Urgent", "Urgent"),
                            ("High", "High"),
                            ("Normal", "Normal"),
                            ("Low", "Low"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("feedback", models.TextField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assigned_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Task",
                "verbose_name_plural": "Tasks",
            },
        ),
    ]
