# Generated by Django 5.0 on 2024-01-04 23:22

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0007_subscriptionattendance"),
    ]

    operations = [
        migrations.CreateModel(
            name="WalkInType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created_at"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="modified_at"),
                ),
                (
                    "is_safe_deleted",
                    models.BooleanField(default=False, verbose_name="is_safe_delete"),
                ),
                ("name", models.CharField(max_length=155, verbose_name="name")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="price"
                    ),
                ),
            ],
            options={
                "verbose_name": "WalkIn Type",
                "verbose_name_plural": "WalkIn Types",
            },
        ),
        migrations.CreateModel(
            name="WalkInUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created_at"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="modified_at"),
                ),
                (
                    "is_safe_deleted",
                    models.BooleanField(default=False, verbose_name="is_safe_delete"),
                ),
                (
                    "full_name",
                    models.CharField(max_length=255, verbose_name="full_name"),
                ),
                (
                    "mobile",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None, verbose_name="mobile"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="payment_method",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="total_amount"
                    ),
                ),
                (
                    "discount_type",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="discount_type",
                    ),
                ),
                (
                    "price_after_discount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        verbose_name="price_after_discount",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="notes"),
                ),
                (
                    "walk_in_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="walk_in_users",
                        to="subscriptions.walkintype",
                    ),
                ),
            ],
            options={
                "verbose_name": "WalkIn User",
                "verbose_name_plural": "WalkIn Users",
            },
        ),
    ]
