# Generated by Django 5.0 on 2024-01-05 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0009_walkinuser_added_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="discount_type",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="discount_type"
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="payment_method",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="payment_method"
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="price_after_discount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=6,
                null=True,
                verbose_name="price_after_discount",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="sales_person",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sales_person_subscriptions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=6, null=True, verbose_name="total_amount"
            ),
        ),
    ]
