# Generated by Django 5.0 on 2024-01-05 19:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0010_subscription_discount_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscriptionattendance",
            name="is_attended",
        ),
        migrations.AddField(
            model_name="subscription",
            name="comments",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subscriptionattendance",
            name="checkin_time",
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name="subscriptionattendance",
            name="checkout_time",
            field=models.TimeField(null=True),
        ),
    ]
