# Generated by Django 5.0 on 2024-01-10 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0012_alter_freezingrequest_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="discount",
            field=models.FloatField(blank=True, null=True, verbose_name="discount"),
        ),
        migrations.AddField(
            model_name="walkinuser",
            name="discount",
            field=models.FloatField(blank=True, null=True, verbose_name="discount"),
        ),
    ]
