# Generated by Django 5.0 on 2024-01-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0014_subscription_added_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="price",
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="price_after_discount",
            field=models.DecimalField(
                decimal_places=3,
                max_digits=10,
                null=True,
                verbose_name="price_after_discount",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=3, max_digits=10, null=True, verbose_name="total_amount"
            ),
        ),
        migrations.AlterField(
            model_name="walkintype",
            name="price",
            field=models.DecimalField(
                decimal_places=3, max_digits=10, verbose_name="price"
            ),
        ),
        migrations.AlterField(
            model_name="walkinuser",
            name="price_after_discount",
            field=models.DecimalField(
                decimal_places=3, max_digits=10, verbose_name="price_after_discount"
            ),
        ),
        migrations.AlterField(
            model_name="walkinuser",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=3, max_digits=10, verbose_name="total_amount"
            ),
        ),
    ]
